### ISSUE TITLE
Translate to other languages, particularly Chinese

### ISSUE THREAD

**Issue by lispking** [MystenLabs/walrus-docs#150]
### Description

Thank you for offering such powerful technology.

I'm more than happy to help by translating this book into Chinese to attract more like-minded friends to learn and progress together.

If you are embarking on this task, do you have any additional suggestions? Should I go ahead and merge it into this repository by submitting a Pull Request (PR)?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by mlegner** [comment]
Thanks a lot for the initiative, @lispking! We definitely want to support users in the language they feel most comfortable in. For translations of our docs, I see 3 main possibilities:
1. Keep the translations in this repository. This gives us a lot of control but also a lot of overhead. Also, the tool we use (mdBook) doesn't really support multilingual docs well.
2. Keep the translations in separate repositories, possibly owned by community members such as yourself. This would reduce our overhead but may also mean that the content gets out of sync pretty quickly (as we will keep changing the docs over the coming months). Would you be willing to maintain something like this?
3. Simply let users use their favorite AI tool like Google Translate to browse our site. This is of course not perfect, but would be by far the most maintainable solution. Maybe you could take a look at the [Chinese translation created by Google Translate](https://docs-blob-store.translate.goog/?_x_tr_sl=auto&_x_tr_tl=zh-CN&_x_tr_hl=en&_x_tr_pto=wapp) and check if it is of sufficient quality?

We will also discuss the different options within the team and get back to you in the coming days.

**Comment by lispking** [comment]
https://github.com/google/mdbook-i18n-helpers
Discovered this library, quite interesting. It seems that everyone is using this plugin in mdbook to implement it.

**Comment by lispking** [comment]
@mlegner I tried translating Chinese and it seems to work with this method. I've submitted part of the translation in the PR, and it looks quite user-friendly.

> https://github.com/google/mdbook-i18n-helpers Discovered this library, quite interesting. It seems that everyone is using this plugin in mdbook to implement it.
> 
> I have already forked the branch and it's under verification: https://github.com/lispking/walrus-docs

**Comment by lispking** [comment]
Translation effect can be viewed here: https://rustx-labs.github.io/walrus-docs/

**Comment by mlegner** [comment]
Thank you so much for all your work on this, @lispking. I will take a look at the setup and ask one of the native Chinese speakers on the team to take a look at the translation.
