### ISSUE TITLE
add walrus steke none id retrieve 

### ISSUE THREAD

**Issue by Usamahmk** [MystenLabs/walrus-docs#167]
### Description

I would like to be able to fech node id using CLI  so it will be more easier to stake cause now you cant get the node id only on the site you can get it 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by Usamahmk** [comment]
Since you have the stake function using the CLI I think having the command that will print the node details will make it easier the for staker that stake  through CLI,  He don`t have to go back to the staking site to get the nodes details he can just copy the id there and stake or have to export his wallet`s keys and import to external wallet so he will to the site and then stake.

**Comment by mlegner** [comment]
Thanks for the clarification. We will add the node IDs to the output of the `walrus info --dev` output in an upcoming release.

cc @giac-mysten

**Comment by mlegner** [comment]
This has been added to the `walrus info --dev` in the latest development version and will be available in next week's 1.5.0 release.
