### ISSUE TITLE
Split a storage should return storages

### ISSUE THREAD

**Issue by yanganto** [MystenLabs/walrus-docs#169]
### Description

The split storage functions should return rest of storage.
https://github.com/MystenLabs/walrus-docs/blob/d8f3243845278616328a94f87fadf1d0a778e0e7/contracts/walrus/sources/system/storage_resource.move#L53
https://github.com/MystenLabs/walrus-docs/blob/d8f3243845278616328a94f87fadf1d0a778e0e7/contracts/walrus/sources/system/storage_resource.move#L69

Current functions only return the first storage and the optional rest of part will lose control.  If these functions suppose to do this, the naming may consider changed.  The current behavior is much like `resize` not `split`.

Also, there is [remainder](https://doc.rust-lang.org/std/str/struct.Split.html#method.remainder) in split struct in Rust.  This maybe a good design pattern for reference.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by mlegner** [comment]
Thanks for creating this issue, @yanganto!

I'm not quite sure I understand the request though. What these functions do is (i) modify the `Storage` that is passed in in-place and (ii) return the newly-created split-off piece. This second piece can then be transferred to the intended owner in a PTB or used for further functions.

As `Storage` does not implement `drop`, it is not possible to just "lose control" of a `Storage` object as the Move compiler will complain.

cc @karlwuest

**Comment by yanganto** [comment]
Hi @mlegner, @karlwuest 
Sorry about this.  I now know what you means, the original one is shrink and split off a new one.
