### ISSUE TITLE
Provide deployment testnet address for each contract

### ISSUE THREAD

**Issue by yanganto** [MystenLabs/walrus-docs#173]
### Description

Please provide these contract address for the testnet, so we will easy to work on top of these.  Many thanks. :pray: 

https://github.com/MystenLabs/walrus-docs/blob/d8df15ad091fed517a004178bb347f2ea7592352/contracts/wal/Move.toml#L11
https://github.com/MystenLabs/walrus-docs/blob/d8df15ad091fed517a004178bb347f2ea7592352/contracts/wal_exchange/Move.toml#L12
https://github.com/MystenLabs/walrus-docs/blob/d8df15ad091fed517a004178bb347f2ea7592352/contracts/walrus/Move.toml#L13

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by mlegner** [comment]
@karl What would be the best way of including our deployment info here?

**Comment by karlwuest** [comment]
The addresses are included in the Move.lock, which should automatically make sure that the correct addresses are used when the contract is included as a dependency (see [here](https://docs.sui.io/concepts/sui-move-concepts/packages/automated-address-management)).

@yanganto does this not work for you? If so, can you let me know what you trying, s.t. I can reproduce the issue?

**Comment by yanganto** [comment]
Thanks.
Here is the answer.
https://github.com/MystenLabs/walrus-docs/blob/d8df15ad091fed517a004178bb347f2ea7592352/contracts/wal/Move.lock#L30-L34
